name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: install deps
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install clang-tidy
      - name: Run tests
        run: |
          cmake -Bbuild && cd build
          cmake --build .
          make test
        